// Copyright 2009 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ========================================================================

import "oaidl.idl";

[
  object,
  uuid(57E37502-65A5-484a-A035-C1608B2626EA),
  dual,
  helpstring("GoogleUpdate3Web Control"),
  pointer_default(unique)
]
interface IGoogleUpdate3WebControl : IDispatch {
  [id(1)] HRESULT createOmahaMachineServerAsync(
      [in] VARIANT_BOOL create_elevated,
      [out, retval] IDispatch** async_status);

  [id(2)] HRESULT createOmahaUserServer([out, retval] IDispatch** server);

  [id(3)] HRESULT getInstalledVersion([in] BSTR guid_string,
                                      [in] VARIANT_BOOL is_machine,
                                      [out, retval] BSTR* version_string);

  [id(4)] HRESULT crossInstall([in] BSTR extra_args);

  [id(5)] HRESULT launchAppCommand([in] BSTR guid_string,
                                   [in] VARIANT_BOOL is_machine,
                                   [in] BSTR cmd_id);
};

[
  object,
  uuid(6F65D62B-2F32-4483-9028-176C30B2389D),
  dual,
  helpstring("Google Update OneClick Control"),
  pointer_default(unique)
]
interface IGoogleUpdateOneClick : IDispatch
{
  // Deprecated. Will be removed in the next release of OneClick.
  [id(1), helpstring("Install")] HRESULT Install(
      [in] BSTR cmd_line_args,
      [in] VARIANT* success_callback,
      [in] VARIANT* failure_callback);

  // New, easier way of calling Install. Use this for newer web pages.
  [id(2), helpstring("Install2")] HRESULT Install2([in] BSTR extra_args);

  [id(3), helpstring("GetInstalledVersion")] HRESULT GetInstalledVersion(
      [in] BSTR guid_string,
      [in] VARIANT_BOOL is_machine,
      [out, retval] BSTR* version_string);

  [id(4), helpstring("GetOneClickVersion")] HRESULT GetOneClickVersion(
      [out, retval] long* version);

  // TODO(omaha): Remove this if LaunchAppCommand only ships in Omaha3
  [id(5), helpstring("LaunchAppCommand")] HRESULT LaunchAppCommand(
      [in] BSTR app_guid,
      [in] VARIANT_BOOL is_machine,
      [in] BSTR cmd_id);
};

[
  uuid(b627c883-e979-4873-80b3-ddd0b658b56a),
  version(1.0),
  helpstring("Google Update Browser Plugins 3.0 Type Library")
]
library GoogleUpdateControlLib {
  importlib("stdole2.tlb");

  interface IGoogleUpdateOneClick;
  interface IGoogleUpdate3WebControl;

  [
    uuid(c442ac41-9200-4770-8cc0-7cdb4f245c55),
    helpstring("Google Update OneClick Control Class")
  ]
  coclass GoogleUpdateOneClickControlCoClass
  {
    [default] interface IGoogleUpdateOneClick;
  };

  [
    uuid(c3101a8b-0ee1-4612-bfe9-41ffc1a3c19d),
    helpstring("GoogleUpdate3Web Control Class")
  ]
  coclass GoogleUpdate3WebControlCoClass {
    [default] interface IDispatch;
  };
};
